### ISSUE TITLE
Test for v0.2.1

### ISSUE THREAD

**Issue by mbosio85** [seqeralabs/tower-agent#17]
Items to test for v0.2:

*Single user tests*
- [x] Create new Agent credentials
- [x] Create new slurm  CE with agent credentials for at least 2 users. `User A`and `User B`
- [x] Download en execute the agent in linux environment on a login node for a slurm cluster
    - [x] Requires having access to a slurm cluster/scheduler with multiple users
- [x] Launch a pipeline with new CE and agent credentials (with agent running)
- [x] Check it works for follow up (tracing) with agent on Launch with agent running
- [x] Check it works for follow up (tracing) with agent not running
- [x] Check correct behavior when agent is not running
- [x] Check that it is not possible to run two agents with same user and connection ID
- [x] Start an Agent, remove the personal token used at Tower UI, wait 30 minutes for session expiration. The Agent has to fail when trys to reconnect.

*Multi user tests*

 - [x] `User B` (without agent running) can access the logs of the `User A` pipeline when  `User A` has the agent running
 - [x] Ensure that `User B` cannot access logs of `User A`pipeline if the agent of `User A`is not running 
 - [x] Ensure `User B`can **not** access logs of `User A`if `User B`has their agent running 
 - [x] If `User B`  relaunches a pipeline previously executed by `User A` . The relaunched pipeline  is run using `User B` agent regardless if `User A` agent is  running or not.

**Quick summary**
- Works as expected for multiple users, provided the permissions in the cluster are correctly set:
   - If both `User A` and `User B` have write access to `Workdir` and both pertain to the same user `group`, everything works fine including the resume. This because both user can edit the files generated by each other
   - If `User A` and `User B` are not from the same user `group`, even if they can write inside `Workdir`, they cannot write on each other's files. This causes strange errors wen relaunching + resume pipelines from the other user.
      - Get errors like executing the same relaunch + resume 
      - >Unknown error accessing project `pditommaso/rnaseq-nf` -- Repository may be corrupted: /home/seq_slurm_1/workfolder/.nextflow/pipelines/78d5505f/pditommaso/rnaseq-nf" 
      - >Launching `pditommaso/rnaseq-nf` [ridiculous_edison] - revision: c1f7039ddf [master] Can't open cache DB: /home/seq_slurm_1/workfolder/.nextflow/cache/0c390485-3219-44a2-a988-493027c14552/db Nextflow needs to be executed in a shared file system that supports file locks. Alternatively you can run it in a local directory and specify the shared work directory by using by `-w` command line option.
- **A note**: If `User A` agent with `User A` tokens is executed from a shell of `User C` (e.g. ubuntu in our slurm environment) we will see a disconnect between Tower and Slurm
   - In Tower the pipeline will look as executed by `User A`
   - In the cluster, the job submission will be done by `User C`
   - @jordeu Do we need to put a warning somewhere for users to keep safely their credentials to avoid having this?

**Comment by jordeu** [comment]
I get the same `.nextflow/history.lock (Permission denied)` error when I resume a failed job, but also if I relaunch without resume.

**Comment by jordeu** [comment]
@mbosio85 can we close this issue?

**Comment by mbosio85** [comment]
Yes, it can be closed
