### ISSUE TITLE
Do not allow insecure connections in any way.

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-agent#25]
## Description
- Do not allow to use non-SSL connections in any way
- Do not allow to use self-signed certificates.
- Review how and which CA certificates are managed. [more info](https://www.graalvm.org/reference-manual/native-image/CertificateManagement/)

**Comment by pditommaso** [comment]
Hold on, we had a specific request to not have this. Is it really needed?

**Comment by jordeu** [comment]
Here I'm talking about this https://github.com/seqeralabs/tower-agent/issues/16 issue that it is already implemented. If this flag is not set connection to a HTTP server is not allowed, only HTTPS.

What was this request about?

**Comment by pditommaso** [comment]
To not allow insecure connection with an --insecure flag 😄

**Comment by jordeu** [comment]
Ok, I agree. In fact, this was my first idea but I thought that maybe I was to much "security paranoic" :smile: . 

Let me rewrite this issue then.
