### ISSUE TITLE
The user name can be null

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-agent#33]
Using the method below can cause the client to report a null user name 

https://github.com/seqeralabs/tower-agent/blob/bbfe9d2af55bb39dbb57954e19beccdaf236eed1/src/main/java/io/seqera/tower/agent/Agent.java#L185-L185

- [ ] Use instead `System.getProperty('user.name')` which is more reliable 
- [ ] Add a mini validation on client to report an error in this info is missing
- [ ] Extend this approach to work dir

**Comment by jordeu** [comment]
> Extend this approach to work dir

What do you mean? Right now it is validated that it is a valid path string. It is not validated that the path exists. Do you think that we also need to validate that it exists?

**Comment by pditommaso** [comment]
I mean getting the user home via `System.getProperty('user.home')` and checking we are sending  null attributes to tower

**Comment by jordeu** [comment]
Ok. And what about checking if the `workDir` exists? Do you think that it must exists a priory? If it not exists Tower will create it, but may be it is better to enforce it to avoid possible errors when writing it.

**Comment by pditommaso** [comment]
> Do you think that it must exists a priory?

yeah, let's have the user to create this. Better to prevent too many implicits for this feature.

**Comment by jordeu** [comment]
@JoseEspinosa we've new release:
 https://github.com/seqeralabs/tower-agent/releases/tag/v0.4.1 

please test it! Thanks!

**Comment by pditommaso** [comment]
More fun Jordi! now it's this 😆 

```
[643/e0ae0409-9356-42df-baf5-db9de9635333] InfoMessage[userName='?'; workDir='/users/cn/jespinosa/scratch'; agentVersion='0.4.1']
```

**Comment by pditommaso** [comment]
Should we add an option to pick the user name?

**Comment by pditommaso** [comment]
or maybe trying to fallback to env `USER` ?

**Comment by jordeu** [comment]
What if we do the opposite? We can give priority to the `USER` env and if it doesn't exists then fallback to `System.getProperty("user.name")`.

**Comment by pditommaso** [comment]
I agree. Handle also `?` as missing user name error

**Comment by jordeu** [comment]
You mean to fail on that case and force the user to set `USER` env?

**Comment by pditommaso** [comment]
to fail when the `user == '?'`

**Comment by JoseEspinosa** [comment]
Will give it a try 🍬 Thanks!

**Comment by jordeu** [comment]
@JoseEspinosa release v0.4.2 is out.

**Comment by JoseEspinosa** [comment]
Tried it and was able to create the environment using the agent 🎉
Thanks!
