### ISSUE TITLE
Tower agent not fetching correct files via github API

### ISSUE THREAD

**Issue by sandsebi** [seqeralabs/tower-agent#43]
I'm trying to run the following pipeline on Tower:
```
nextflow run https://github.com/enasequence/covid-sequence-analysis-workflow
		 -name test-V2
		 -with-tower
		 -r v2-api-migration
		 -main-script nanopore/nanopore.nf
```
But it errors out with the following:
```
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/enasequence/covid-sequence-analysis-workflow/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/enasequence/covid-sequence-analysis-workflow/contents/main.nf
```

Ideally as I've specified the `Revision number` which in my case is the branch name, the Github API URL's should look like:
`https://api.github.com/repos/enasequence/covid-sequence-analysis-workflow/contents/nextflow.config?ref=v2-api-migration` and
`https://api.github.com/repos/enasequence/covid-sequence-analysis-workflow/contents/main.nf?ref=v2-api-migration` right?

I'm using Tower agent on LSF.
Nextflow module version: nextflow-21.10.6-gcc-9.3.0-tkuemwd

**Comment by pditommaso** [comment]
The problem is that the repository does not have either the `nextflow.config` or `main.nf` file in the project root

**Comment by sandsebi** [comment]
It does have both on the branch `v2-api-migration`

**Comment by pditommaso** [comment]
Unfortunely it's not enough. There must be at least the `nextflow.config` file (even empty) in the default branch

**Comment by sandsebi** [comment]
Ok thanks 👍 Would have been helpful to document clearly, the need for having a `main.nf` and a `nextflow.config` file at the root of the repo.
